puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
]

puddle/core/urls.py
from django.urls import path
from core.forms import LoginForm
from . import views
from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),

]

puddle/dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

puddle/item/urls.py
# item.urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns =[
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


# for loggin in 
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs= {
        'placeholder': "Please Enter your Username",
        'class' : 'w-full px-6 py-4 rounded-xl'
    }
    ))
     
    password = forms.CharField(widget=forms.PasswordInput(attrs= {
        'placeholder': "Please Enter your Password",
        'class' : 'w-full px-6 py-4 rounded-xl'
    }
    ))


# for signing up
class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs= {
        'placeholder': "Please Enter your Username",
        'class' : 'w-full px-6 py-4 rounded-xl'
    }
    ))

    email = forms.CharField(widget=forms.EmailInput(attrs= {
        'placeholder': "Please Enter your Email address",
        'class' : 'w-full px-6 py-4 rounded-xl'
    }
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs= {
        'placeholder': "Please Enter your Password",
        'class' : 'w-full px-6 py-4 rounded-xl'
    }
    ))
    password2 = forms.CharField(widget=forms.TextInput(attrs= {
        'placeholder': "Please confirm your password",
        'class' : 'w-full px-6 py-4 rounded-xl'
    }
    ))

puddle/core/views.py
from django.shortcuts import redirect, render
from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    context = {
        'items': items,
        'categories': categories,
    }
    return render(request, 'core/index.html', context=context)


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    else:
        form = SignupForm()

    context = {
        'form': form,
    }

    return render(request, 'core/signup.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('/login/')

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Puddle</title>
</head>

<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>
        <div class="space-x-6">
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
            <a href="#" class="px-3 py-3 font-semibold bg-violet-500 text-white rounded-xl hover: bg-teal-700"> Hi
                {{user.username}}</a>
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Add Item</a>

            <a href="{% url 'conversation:inbox' %}"
                class="px-6 py-6 font-semibold bg-teal-500 text-white rounded-xl hover: bg-teal-700">Inbox</a>
            <a href="{% url 'dashboard:index' %}"
                class="px-6 py-6 font-semibold bg-gray-500 text-white rounded-xl hover: bg-gray-700">dashboard</a>
            <a href="{% url 'core:logout' %}"
                class="px-6 py-6 font-semibold bg-gray-500 text-white rounded-xl hover: bg-gray-700">log Out</a>

            {% else %}
            <a href="{% url 'core:signup' %}"
                class="px-6 py-6 font-semibold bg-teal-500 text-white rounded-xl hover: bg-teal-700">Sign Up</a>
            <a href="{% url 'core:login' %}"
                class="px-6 py-6 font-semibold bg-gray-500 text-white rounded-xl hover: bg-gray-700">Log in</a>

            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}

    </div>

    <footer class="px-6 py-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold  text-gray-400">About</h3>

            <p class="text-lg text-gray-500">Lorem Ipsum. Something interesting....</p>

        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold  text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
                </li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms and conditions</a></li>

            </ul>


        </div>

    </footer>

</body>

</html>

puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
<h1>The Contact Page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Items</h2>
    <div class="grid grid-cols-3 gap-6">
        {% for item in items %}
        <div class="border border-gray-300 rounded-lg p-4">
            <a href="{% url 'item:detail' pk=item.id %}">
                <div class="w-56 h-56 overflow-hidden">
                    <img src="{{item.image.url}}" class=" object-cover w-full h-full border" alt="some image">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.name}}</h2>
                    <p class="text-gray-500">Price : {{item.price}}</p>
                </div>

            </a>
        </div>
        {% endfor %}

    </div>
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="#">

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{category.name}}</h2>
                    <p class="text-gray-500">{{category.items.count}} items</p>

                </div>

            </a>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

puddle/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="post" action=".">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
            {{ form.username.errors }}

        </div>        

        

        <div class="mb-3">
            <label class="inline-block mb-2">Enter password</label><br>
            {{ form.password }}
            {{ form.password.errors }}

        </div>   

     
        {% if form.errors or form.non_field_errors %}

            <div class="mb-6 p-6 bg-red-100 rounded-xl">

                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}  

            </div>

        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 text-white" type="submit">Submit</button>

    </form>

</div>
{% endblock %}

puddle/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="inline-block mb-2">Username</label>
            {{ form.username}}

        </div>        

        <div class="mb-3">
            <label for="inline-block mb-2">Email</label>
            {{ form.email}}

        </div>   

        <div class="mb-3">
            <label for="inline-block mb-2">Enter password</label>
            {{ form.password1}}

        </div>   

        <div class="mb-3">
            <label for="inline-block mb-2">Confirm password</label>
            {{ form.password2}}

        </div>   

        {% if form.errors or form.non_field_errors %}

            <div class="mb-6 p-6 bg-red-100 rounded-xl">

                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}  

            </div>

        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 text-white" type="submit">Submit</button>

    </form>

</div>
{% endblock %}